jobs:
  - job: ubuntu1604
    displayName: Ubuntu 16.04 Build
    timeoutInMinutes: 0
    pool:
      vmImage: 'Ubuntu 16.04'
    variables:
      BUILD_DIR: '$(Agent.BuildDirectory)/build'
      CMAKE_CXX_FLAGS: '-Wall -Wextra -Wabi -O2'
    steps:
      - script: |
          apt-get install openni2-utils
          add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl -y
          apt-get update -y
          apt-get install libpcl-all -y
          pip install -r requirements.txt
        displayName: 'Install Dependencies'
      - script: |
          python setup.py build_ext -i
          python setup.py install
        displayName: 'Build Library'
      - script: nosetests
        displayName: 'Run Unit Tests'
  - job: osx
    displayName: macOS High Sierra
    timeoutInMinutes: 0
    pool:
      vmImage: 'macOS-10.13'
    variables:
      BUILD_DIR: '$(Agent.BuildDirectory)/build'
      CMAKE_CXX_FLAGS: '-Wall -Wextra -Wabi -O2'
    steps:
      - script: |
          brew install pcl
          pip install -r requirements.txt
        displayName: 'Install Dependencies'
      - script: |
          mkdir $BUILD_DIR && cd $BUILD_DIR
          python setup.py build_ext -i
          python setup.py install
        displayName: 'Build Library'
      - script: nosetests
        displayName: 'Run Unit Tests'
  - job: documentation
    displayName: Generate Documentation
    pool:
      vmImage: 'Ubuntu 16.04'
    variables:
      BUILD_DIR: '$(Agent.BuildDirectory)/docs'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.6'
          addToPath: true
      - script: |
          pip install -r requirements-docs.txt
        displayName: 'Install Dependencies'
      - script: |
          cd $BUILD_DIR
          make html
        displayName: 'Build Documentation'
      - script: |
        displayName: 'Push Generated Documentation To Read the Docs'
  - job: vs2017
    displayName: Windows VS2017 Build
    timeoutInMinutes: 0
    pool:
      vmImage: 'vs2017-win2016'
    strategy:
      matrix:
        x86:
          PLATFORM: 'x86'
          ARCHITECTURE: 'x86'
          GENERATOR: 'Visual Studio 15 2017'
        x64:
          PLATFORM: 'x64'
          ARCHITECTURE: 'x86_amd64'
          GENERATOR: 'Visual Studio 15 2017 Win64'
    variables:
      # BUILD_DIR: '$(Agent.WorkFolder)\build'
      # VCPKG_DIR: '$(Agent.WorkFolder)\vcpkg'
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat'
      CONFIGURATION: 'Release'
      PCL_ROOT: "C:\\Program Files\\PCL 1.9.1"
      PCL_VERSION: "1.9"
      OPENNI_VERSION: "2.2"
      OPENNI_ROOT: "C:\\Program Files\\OpenNI2\\Redist\\"
      NOSEATTR: "not pcl_ver_0_4"
    steps:
      # - script: |
      #     git clone https://github.com/microsoft/vcpkg --depth 1 %VCPKG_DIR%
      #     echo.set(VCPKG_BUILD_TYPE release)>> %VCPKG_DIR%\triplets\%PLATFORM%-windows.cmake
      #     %VCPKG_DIR%\bootstrap-vcpkg.bat
      #     %VCPKG_DIR%\vcpkg.exe version
      #   displayName: 'Bootstrap vcpkg'
      # - script: |
      #     # %VCPKG_DIR%\vcpkg.exe install hogefuga
      #     %VCPKG_DIR%\vcpkg.exe list
      #     pip install -r requirements.txt
      #   displayName: 'Install Dependencies'
      # - script: |
      #     rmdir %VCPKG_DIR%\downloads /S /Q
      #     rmdir %VCPKG_DIR%\packages /S /Q
      #   displayName: 'Free up space'
      - script: |
          SET PATH=%PCL_ROOT%\\bin;%PCL_ROOT%\\3rdParty\\VTK\\bin;%OPENNI_ROOT%;%PATH%
          ps : appveyor\install.ps1
          cd pkg-config
          ps : .\Install-GTKPlus.ps1
          cd ..
          pip install -r requirements.txt
        displayName: 'Install Dependencies'
      - script: |
        python setup.py build_ext -i
        python setup.py install
        displayName: 'Build Library'
      - script: nosetests
        displayName: 'Run Unit Tests'
