language: python 

cache:
  - pip
  - ccache

matrix:
  include:
    - os: linux
      python: "2.7"
    - os: linux
      python: "3.4"
    - os: linux
      python: "3.5"

    # TravisCI TimeLimit 50min
    # numpy error
    # - os: osx
    #   language: generic
    #   env:
    #   - PYTHON_VERSION=2.7.10
    #   - PYENV_ROOT=~/.pyenv
    #   - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
    # - os: osx
    #   language: generic
    #   env:
    #   - PYTHON_VERSION=3.4.3
    #   - PYENV_ROOT=~/.pyenv
    #   - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
    # - os: osx
    #   language: generic
    #   env:
    #   - PYTHON_VERSION=3.5.1
    #   - PYENV_ROOT=~/.pyenv
    #   - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin

# travis_wait 45 brew install pcl --without-vtk --without-qt;
before_install:
  - if [[ $TRAVIS_OS_NAME = "osx" ]]; then
      brew update >/dev/null;
      brew outdated pyenv || brew upgrade --quiet pyenv;
      brew install homebrew/boneyard/pyenv-pip-rehash;
      brew tap homebrew/science;

      PYTHON_CONFIGURE_OPTS="--enable-unicode=ucs2" pyenv install -ks $PYTHON_VERSION;
      pyenv global $PYTHON_VERSION;
      python --version;

      brew search versions/pcl;
      travis_wait 45 brew install pcl --without-qt;
    fi

  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then
      sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl -y;
      sudo apt-get update -y;
      
      travis_wait 45 make -j4
      travis_wait 45 sudo make install

      sudo apt-get install libpcl-all -y;
    fi


install:
  - pip install --upgrade pip
  - pip install cython==0.25.2
  - pip install numpy
  - pip install coveralls
  - python setup.py build_ext -i
  - python setup.py install

# pcl base 1.7.2
# - python examples\official\Recognition\cpython correspondence_grouping.py pcldata\tutorials\correspondence_grouping\milk.pcd pcldata\tutorials\correspondence_grouping\milk_cartoon_all_small_clorox.pcd
script:
  - coverage run --parallel-mode --source=tests/test.py
  - coverage run --parallel-mode --source=tests/test_registration.py
  # # examples_command_172.txt
  # # Filtering
  # - python examples\official\Filtering\PassThroughFilter.py
  # - python examples\official\Filtering\project_inliers.py
  # - python examples\official\Filtering\remove_outliers.py -r Radius
  # - python examples\official\Filtering\remove_outliers.py -r Condition
  # - python examples\official\Filtering\VoxelGrid_160.py
  # - python examples\official\Filtering\statistical_removal.py
  # - python examples\official\IO\pcd_read.py
  # # KdTree
  # - python examples\official\kdtree\kdtree_search.py
  # # keypoints
  # # NG(RangeImage Link Error)
  # - python examples\official\keypoints\narf_keypoint_extraction.py
  # # octree
  # - python examples\official\octree\octree_search.py
  # - python examples\official\Segmentation\cluster_extraction.py
  # - python examples\official\Segmentation\cylinder_segmentation.py
  # - python examples\official\surface\concave_hull_2d.py
  # - python examples\official\surface\resampling.py

after_success:
  - coverage combine
  - coveralls