language: python 


matrix:
  include:
    - os: linux
      python: "2.7"
    - os: linux
      python: "3.4"
    - os: linux
      python: "3.5"

    # TravisCI TimeLimit 50min
    # numpy error
    # - os: osx
    #   language: generic
    #   env:
    #   - PYTHON_VERSION=2.7.10
    #   - PYENV_ROOT=~/.pyenv
    #   - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
    # - os: osx
    #   language: generic
    #   env:
    #   - PYTHON_VERSION=3.4.3
    #   - PYENV_ROOT=~/.pyenv
    #   - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
    # - os: osx
    #   language: generic
    #   env:
    #   - PYTHON_VERSION=3.5.1
    #   - PYENV_ROOT=~/.pyenv
    #   - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin

# travis_wait 45 brew install pcl --without-vtk --without-qt;
before_install:
  - if [[ $TRAVIS_OS_NAME = "osx" ]]; then
      brew update >/dev/null;
      brew outdated pyenv || brew upgrade --quiet pyenv;
      brew install homebrew/boneyard/pyenv-pip-rehash;
      brew tap homebrew/science;

      pyenv install -ks $PYTHON_VERSION;
      pyenv global $PYTHON_VERSION;
      python --version;

      brew search versions/pcl;
      travis_wait 45 brew install pcl --without-qt;
    fi

  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then
      sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl -y;
      sudo apt-get update -y;
      
      travis_wait 45 make -j4
      travis_wait 45 sudo make install

      sudo apt-get install libpcl-all -y;
    fi


install:
  - pip install --upgrade pip
  - pip install cython==0.25
  - pip install numpy
  - python setup.py build_ext -i
  - python setup.py install

# pcl base 1.7.2
# - python examples\official\Recognition\cpython correspondence_grouping.py pcldata\tutorials\correspondence_grouping\milk.pcd pcldata\tutorials\correspondence_grouping\milk_cartoon_all_small_clorox.pcd
script:
  - python tests/test.py
  - python tests/test_registration.py


